modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "https://github.com/Crendgrim/ToggleSubtitles/issues"
license = "LGPL-3.0"

[[mods]]
modId = "togglesubtitles"
version = "${mod_version}"
displayName = "Toggle Subtitles"
authors = "Crendgrim"
description = '''
Adds a key bind to toggle subtitles
'''
logoFile = "togglesubtitles.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.togglesubtitles]]
modId = "minecraft"
type = "required"
mandatory = true
versionRange = "${minecraft_version_range_forge}"
ordering = "NONE"
side = "BOTH"
